# Generated by Django 4.0.5 on 2022-06-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
