# Generated by Django 4.0.5 on 2022-06-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0002_word_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
