# Generated by Django 4.0.5 on 2022-06-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0003_word_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_daily_words',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
