# Generated by Django 4.0.5 on 2022-06-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0004_user_num_daily_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
