# Generated by Django 4.0.5 on 2022-06-14 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0005_word_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='is_new',
        ),
        migrations.AddField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name=datetime.datetime(1970, 1, 1, 0, 0)),
            preserve_default=False,
        ),
    ]
