# Generated by Django 4.0.5 on 2022-06-14 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0006_remove_word_is_new_word_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
