# Generated by Django 4.0.5 on 2022-06-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0007_alter_word_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=30),
        ),
        migrations.AddField(
            model_name='word',
            name='timezone',
            field=models.CharField(default='UTC', max_length=30),
        ),
    ]
