# Generated by Django 4.0.5 on 2022-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0008_user_timezone_word_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='timezone',
        ),
        migrations.AddField(
            model_name='word',
            name='timezone_offset',
            field=models.FloatField(default=0),
        ),
    ]
