# Generated by Django 4.0.5 on 2022-06-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0009_remove_word_timezone_word_timezone_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='timezone_offset',
            field=models.IntegerField(default=0),
        ),
    ]
