# Generated by Django 4.0.5 on 2022-06-15 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0010_alter_word_timezone_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='timezone_offset',
        ),
        migrations.AddField(
            model_name='word',
            name='created_at_local',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
